### ISSUE TITLE
Server Error by Azuriom Page by connecting to Litebans

### ISSUE THREAD

**Issue by TabZz147** [AzuriomCommunity/Plugin-LiteBans#8]
Hi, i get an Server Error 500 by opening the url by my azuriom webpage. my entry datas are correct, can u help please

**Comment by MrMicky-FR** [comment]
Please send the logs located in the `storage/logs` folder

**Comment by TabZz147** [comment]
[log.txt](https://github.com/user-attachments/files/17607733/log.txt)
the website is on my webhosting provider "netcup" and i try to connect to my linux server by OVH;

**Comment by MrMicky-FR** [comment]
The database credentials filled in the settings are not correct

**Comment by TabZz147** [comment]
i check the settings, but they are correct, 100%..

**Comment by MrMicky-FR** [comment]
Look yourself at your logs, SQL `Connection refused`, so something is wrong

**Comment by TabZz147** [comment]
I'll check the firewall settings on the Linux server, maybe the IP is blocked by the web server and therefore no connection. Ty
